# Generated by Django 5.1.1 on 2025-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apr2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(unique=True)),
                ('shipmentUser', models.CharField(max_length=200)),
                ('shipmentCategory', models.CharField(max_length=200)),
                ('shipmentQuantity', models.IntegerField()),
            ],
        ),
    ]
